### PR TITLE
New site redesign

### PR DESCRIPTION
**Pull request by maya**
# ⚠️ 🚧 Do not merge  🚧 ⚠️

This is the new redesign for dotgov.gov. 

😎  Preview: https://federalist-proxy.app.cloud.gov/preview/gsa/dotgov-home/site-updates/

### TODO:

- [ ] Further content work 
- [ ] Approval from OGP

### CODE REVIEW

**Comment by konklone** [comment]
Noting one small blocker before the merge - it's using the inaccurate text around certificates:

screen shot 2017-09-20 at 10 17 32 am

I think this should probably just be removed altogether, rather than fixed - I'm losing faith in the ability of this text to be deployed in an accurate, consistent manner. I can handle that before the merge.

**Comment by maya** [comment]
@konklone here is the banner code for the edits: https://github.com/GSA/dotgov-home/blob/site-updates/_includes/components/banner.html I used the text that was on the USWDS site with the assumption that the banner component was brought back with accurate content: https://standards.usa.gov/components/headers/basic/

**Comment by konklone** [comment]
Yes, the one on usa.gov is correct. 

The standards.usa.gov one is not. I'm pushing the team to fix it there too, since your assumption that standards.usa.gov would have the most up to date text was quite reasonable.

**Comment by maya** [comment]
@konklone banner text updated to the correct text in ad541ae. Thanks for advocating this with the USWDS project.

**Pull request merged**
